version: '3.8'

services:
  image_stylist:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: image_stylist
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - PORT=8081
      - FORCE_CPU_FLAG=true
    volumes:
      - ./src:/app/src  # For development: allows changing code without rebuilding
      - image_stylist_cache:/app/.cache

volumes:
  image_stylist_cache:  # Persistent volume for model cache
